feat: user discounts
SocialGouv/carte-jeune-engage-v2 pull request #23
Opened 2024-01-31 11:15 UTC by HoreKk

2024-02-01 21:27 UTC, ClementNumericite requested changes
Des petits ajustement d'implem
Dans l'ensemble LGTM

2024-02-01 21:27 UTC, ClementNumericite commented on webapp/src/server/api/routers/coupon.ts
>        const coupons = await ctx.payload.find({
est ce qu'on devrait pas gérer le `offer.validityTo` ici aussi ?

2024-02-01 21:28 UTC, ClementNumericite commented on webapp/src/pages/dashboard/wallet/index.tsx
> +const WalletNoData = ({ kind }: { kind: "in-store" | "online" }) => {
ça a des quelques impacts annexes attention

2024-02-02 08:56 UTC, HoreKk commented on webapp/src/pages/dashboard/wallet/index.tsx
> +const WalletNoData = ({ kind }: { kind: "in-store" | "online" }) => {
Ouais je sais pas pourquoi j'ai voulu changer, Offer['kind'] c'est mieux => 9b8a046

2024-02-02 08:56 UTC, HoreKk commented on webapp/src/pages/dashboard/wallet/index.tsx
> +    offerKind?: "in-store" | "online";
Same => 9b8a046

2024-02-05 09:32 UTC, merged